name: Deploy Python App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IP }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/NEtpython

            git pull origin main

            pip3 install -r requirements.txt

            pm2 delete frontpyth || true

            pm2 start "streamlit run app.py --server.port 8501 --server.address 0.0.0.0" --name frontpyth

            pm2 save
